### ISSUE TITLE
DPS310_Advanced not passing on non-default I2C address

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_DPS310#21]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=60&t=189700

The `DPS310_Advanced` subclass needs to pass the `address` parameter on to super. Instead, it's passing the `_DPS310_DEFAULT_ADDRESS` const:
https://github.com/adafruit/Adafruit_CircuitPython_DPS310/blob/8c4112e7f1aeb3dcf840492ab488d0059a1b2b0e/adafruit_dps310/advanced.py#L200

**Comment by ladyada** [comment]
@caternuson i can put together a patch or you can - either way

**Comment by caternuson** [comment]
@ladyada tis but a wee wittle fix. got it with #22. :)

**Comment by tekktrik** [comment]
Is this solved then?

**Comment by caternuson** [comment]
Probably. But let's wait till there's a release so it gets in bundle and can then have the forum poster try it out.

**Comment by caternuson** [comment]
They report success:
https://forums.adafruit.com/viewtopic.php?f=60&t=189700&p=918650#p918590

Closing.
