### ISSUE TITLE
Update docs for sensor values

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_DPS310#23]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=19&t=192342

Sensor units from Design Guide:
https://docs.circuitpython.org/en/latest/docs/design_guide.html#sensor-properties-and-units

Need to:
- Confirm `pressure` units and change doc string to `hPa`
- Confirm `altitude` units and add to doc string

**Comment by ladyada** [comment]
@tekktrik wanna do this?

**Comment by tekktrik** [comment]
Yeah I got this one!
