### ISSUE TITLE
Code hangs when calling dps310.wait_temperature_ready()

### ISSUE THREAD

**Issue by Vexs** [adafruit/Adafruit_CircuitPython_DPS310#28]
As title, and possibly somehow tied to my other problem #27. 

Calling `dps310.wait_temperature_ready()` will hang forever and not continue. Tried on a pair of dps310 modules from adafruit with the same behavior.

With the code shown below, the print is never called. 

```
import time
import board
from adafruit_dps310.basic import DPS310

i2c = board.I2C()

dps310 = DPS310(i2c)

dps310.wait_temperature_ready()
print('passed readying')

```

**Comment by jposada202020** [comment]
Hello @Vexs
**Comments**
What board are you using?
Also the library wait for good measures of temperature and Pressure when it starts. 
https://github.com/adafruit/Adafruit_CircuitPython_DPS310/blob/b9dc369bf1422f225d52519fdab09b6bf4867052/adafruit_dps310/basic.py#L175
So it will be a good idea to put a print statement after `dps310 = DPS310(i2c)` to see if there is a problem there
Let me know what board are you using and I can test on my side too.
cheers

**Comment by jposada202020** [comment]
@Vexs Will close this for now, feel free to re-open when you have more information and hopefully a traceback.  :). that would really help.
