### ISSUE TITLE
Add altitude

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_DPS310#8]
Add an `altitude` property to return pressure based altitude in meters. Ref BMP280 implementation:
https://github.com/adafruit/Adafruit_CircuitPython_BMP280/blob/f65303074498e07db883e73c067a8b9e491451a2/adafruit_bmp280.py#L355

**Comment by caternuson** [comment]
Don't we want it here also?

**Comment by ladyada** [comment]
oops sorry thought this was the arduino one - i dont think we do altitude calc in the library, only examples?

**Comment by caternuson** [comment]
The CircuitPython BMP280 lib has it? Simple PR FWIW. Not much more than a copy pasta from the BMP280 lib.

**Comment by ladyada** [comment]
we'd rather have it as an example instead of API addition

**Comment by caternuson** [comment]
@ladyada I left the PR open while being gone for a few days. It looks like it got merged and released. Want me to revert to remove and make a new release?

**Comment by ladyada** [comment]
nah its ok!
